### ISSUE TITLE
atrous TypeError

### ISSUE THREAD

**Issue by jaimebayes** [abrazhe/image-funcut#7]
Hi,

I am trying to run atrous file, using tif image (img.tif), using ubuntu14/anaconda2.1.0/python27,  executing this:
>>>import imfun
>>>from imfun import atrous
>>>from scipy.signal import convolve2d
>>>wave = atrous.decompose2d_numpy(img,level=3)
Traceback (most recent call last):

  File "<ipython-input-16-3746439e7f68>", line 1, in <module>
    wave = atrous.decompose2d_numpy(img,level=3)

  File "/home/jaimebayes/anaconda/lib/python2.7/site-packages/imfun/atrous.py", line 232, in decompose2d_numpy
    return [w] + decompose2d(approx,level-1,upphi,boundary)

  File "/home/jaimebayes/anaconda/lib/python2.7/site-packages/imfun/atrous.py", line 155, in decompose2d_weave
    coefs = np.ones((level+1, sh[0], sh[1]),dtype=dtype)

  File "/home/jaimebayes/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 183, in ones
    a = empty(shape, dtype, order)

TypeError: data type "symm" not understood

**Comment by abrazhe** [comment]
Dear jaimebayes, commits 854529725112b861ce4cd26cb11f4289014fb499 and d8432e0bbb7a2aa6e16c7138bf54b187d264c36c should have fixed this error. Sorry for long time it took to get back to the code.
